[package]
name = "zeno-bench"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = { version = "0.9.2", features = ["std"] }
rand_distr = "0.5.1"
zeno-core = {path="../zeno-core"}
zeno-proto = {path="../zeno-proto"}
